# Generated by Django 5.1.7 on 2025-03-15 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madS', '0005_alter_form_created_at_alter_form_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_list', to='madS.form'),
        ),
    ]
