# Generated by Django 5.1.7 on 2025-03-15 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madS', '0005_tag_remove_question_form_remove_comment_form_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='response',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('references', models.TextField(blank=True)),
                ('survey', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='madS.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madS.customuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
