# Generated by Django 5.1.7 on 2025-03-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madS', '0006_alter_response_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Test', max_length=255),
        ),
    ]
