# Generated by Django 5.1.7 on 2025-03-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madS', '0007_alter_survey_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='tags',
            field=models.ManyToManyField(blank=True, to='madS.tag'),
        ),
    ]
