# Generated by Django 5.1.7 on 2025-03-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madS', '0007_article_title'),
        ('madS', '0008_alter_survey_tags'),
    ]

    operations = [
    ]
